apiVersion: v1
kind: Service
metadata:
  name: price-prediction-service
  labels:
    app: price-prediction-app
spec:
  selector:
    app: price-prediction-app  # Must match Deployment labels
  ports:
    - protocol: TCP
      port: 80                 # External port to expose (change if needed)
      targetPort: 5000         # Container's exposed port
  type: NodePort               # Change to LoadBalancer if on a cloud provider
