# Base Python image
FROM python:3.12-slim

# Set working directory inside the container
WORKDIR /myapp

# Copy requirements first to leverage Docker's layer caching
COPY jenkins_project/requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application files
COPY jenkins_project/ /myapp

# Expose the application port
EXPOSE 5000

# Command to run the application
CMD ["python", "app.py"]

